"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import base64
import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,testserver",
    ).split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'equipment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _build_database_config():
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        parsed = urlparse(database_url)
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": parsed.port or 5432,
        }

    postgres_host = os.environ.get("POSTGRES_HOST", "").strip()
    if postgres_host:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "vaultis"),
            "USER": os.environ.get("POSTGRES_USER", "vaultis"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": postgres_host,
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }

    db_path = os.environ.get("DJANGO_DATABASE_PATH", "").strip()
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(db_path) if db_path else BASE_DIR / "db.sqlite3",
    }


DATABASES = {"default": _build_database_config()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Fuseau pour l’affichage (templates |localtime) et les horodatages métier.
# La base reste en UTC tant que USE_TZ=True.

LANGUAGE_CODE = "fr-fr"

_django_tz = os.environ.get("DJANGO_TIME_ZONE", "UTC").strip()
TIME_ZONE = _django_tz or "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# WhiteNoise sert les fichiers depuis STATIC_ROOT (après collectstatic)
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_MAX_AGE = 3600 if not DEBUG else 0

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

MESSAGE_TAGS = {
    message_constants.DEBUG: "secondary",
    message_constants.INFO: "info",
    message_constants.SUCCESS: "success",
    message_constants.WARNING: "warning",
    message_constants.ERROR: "danger",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Nitrokey / NetHSM (adaptateur equipment.adapters.nitrokey)
_backup_root = os.environ.get("NITROKEY_BACKUP_ROOT", "").strip()
NITROKEY_BACKUP_ROOT = Path(_backup_root) if _backup_root else BASE_DIR / "backups" / "nitrokey"
NITROKEY_TRANSFER_MODE = os.environ.get("NITROKEY_TRANSFER_MODE", "auto").strip().lower()
_windows_transfer_dir = os.environ.get("NITROKEY_WINDOWS_TRANSFER_DIR", "").strip()
NITROKEY_WINDOWS_TRANSFER_DIR = Path(_windows_transfer_dir) if _windows_transfer_dir else None
NITROKEY_WINDOWS_SMB_HOST = os.environ.get("NITROKEY_WINDOWS_SMB_HOST", "").strip()
NITROKEY_WINDOWS_SMB_SHARE = os.environ.get("NITROKEY_WINDOWS_SMB_SHARE", "").strip()
NITROKEY_WINDOWS_SMB_REMOTE_DIR = os.environ.get("NITROKEY_WINDOWS_SMB_REMOTE_DIR", "").strip()
NITROKEY_WINDOWS_SMB_USERNAME = os.environ.get("NITROKEY_WINDOWS_SMB_USERNAME", "").strip()
NITROKEY_WINDOWS_SMB_PASSWORD = os.environ.get("NITROKEY_WINDOWS_SMB_PASSWORD", "")
NITROKEY_WINDOWS_SMB_DOMAIN = os.environ.get("NITROKEY_WINDOWS_SMB_DOMAIN", "").strip()
NITROKEY_WINDOWS_SMB_PORT = int(os.environ.get("NITROKEY_WINDOWS_SMB_PORT", "445"))
NITROKEY_WINDOWS_SCP_HOST = os.environ.get("NITROKEY_WINDOWS_SCP_HOST", "").strip()
NITROKEY_WINDOWS_SCP_PORT = int(os.environ.get("NITROKEY_WINDOWS_SCP_PORT", "22"))
_scp_username_file = os.environ.get("NITROKEY_WINDOWS_SCP_USERNAME_FILE", "").strip()
if _scp_username_file:
    NITROKEY_WINDOWS_SCP_USERNAME = Path(_scp_username_file).read_text(encoding="utf-8").strip("\r\n")
else:
    NITROKEY_WINDOWS_SCP_USERNAME = os.environ.get("NITROKEY_WINDOWS_SCP_USERNAME", "").strip()
_scp_password_file = os.environ.get("NITROKEY_WINDOWS_SCP_PASSWORD_FILE", "").strip()
_scp_password = os.environ.get("NITROKEY_WINDOWS_SCP_PASSWORD", "")
_scp_password_b64 = os.environ.get("NITROKEY_WINDOWS_SCP_PASSWORD_B64", "").strip()
if _scp_password_file:
    NITROKEY_WINDOWS_SCP_PASSWORD = Path(_scp_password_file).read_text(encoding="utf-8").strip("\r\n")
elif _scp_password_b64:
    NITROKEY_WINDOWS_SCP_PASSWORD = base64.b64decode(_scp_password_b64).decode("utf-8")
else:
    NITROKEY_WINDOWS_SCP_PASSWORD = _scp_password
NITROKEY_WINDOWS_SCP_REMOTE_DIR = os.environ.get("NITROKEY_WINDOWS_SCP_REMOTE_DIR", "").strip()
_nethsm_user_file = os.environ.get("NITROKEY_NETHSM_USER_FILE", "").strip()
if _nethsm_user_file:
    NITROKEY_NETHSM_USER = Path(_nethsm_user_file).read_text(encoding="utf-8").strip("\r\n")
else:
    NITROKEY_NETHSM_USER = os.environ.get("NITROKEY_NETHSM_USER", "").strip()
_nethsm_password_file = os.environ.get("NITROKEY_NETHSM_PASSWORD_FILE", "").strip()
_nethsm_password = os.environ.get("NITROKEY_NETHSM_PASSWORD", "")
_nethsm_password_b64 = os.environ.get("NITROKEY_NETHSM_PASSWORD_B64", "").strip()
if _nethsm_password_file:
    NITROKEY_NETHSM_PASSWORD = Path(_nethsm_password_file).read_text(encoding="utf-8").strip("\r\n")
elif _nethsm_password_b64:
    NITROKEY_NETHSM_PASSWORD = base64.b64decode(_nethsm_password_b64).decode("utf-8")
else:
    NITROKEY_NETHSM_PASSWORD = _nethsm_password
NITROKEY_NETHSM_VERIFY_TLS = os.environ.get(
    "NITROKEY_NETHSM_VERIFY_TLS",
    "true",
).lower() in ("1", "true", "yes")

# F5 BIG-IP (adaptateur equipment.adapters.f5 — SSH + tmsh)
F5_INTEGRATION = os.environ.get("F5_INTEGRATION", "").strip().lower()
_f5_ssh_user_file = (
    os.environ.get("F5_SSH_USER_FILE", "").strip()
    or os.environ.get("F5_ICONTROL_USER_FILE", "").strip()
)
if _f5_ssh_user_file:
    F5_SSH_USER = Path(_f5_ssh_user_file).read_text(encoding="utf-8").strip("\r\n")
else:
    F5_SSH_USER = (
        os.environ.get("F5_SSH_USER", "").strip()
        or os.environ.get("F5_ICONTROL_USER", "").strip()
    )
_f5_ssh_password_file = (
    os.environ.get("F5_SSH_PASSWORD_FILE", "").strip()
    or os.environ.get("F5_ICONTROL_PASSWORD_FILE", "").strip()
)
_f5_ssh_password = os.environ.get("F5_SSH_PASSWORD", "") or os.environ.get("F5_ICONTROL_PASSWORD", "")
if _f5_ssh_password_file:
    F5_SSH_PASSWORD = Path(_f5_ssh_password_file).read_text(encoding="utf-8").strip("\r\n")
else:
    F5_SSH_PASSWORD = _f5_ssh_password
F5_SSH_PORT = int(os.environ.get("F5_SSH_PORT", "22") or "22")
F5_SSH_SAVE_TIMEOUT = int(os.environ.get("F5_SSH_SAVE_TIMEOUT", "7200") or "7200")
F5_UCS_DEVICE_DIR = os.environ.get("F5_UCS_DEVICE_DIR", "/var/local/ucs").strip() or "/var/local/ucs"
_f5_backup_root = os.environ.get("F5_BACKUP_ROOT", "").strip()
F5_BACKUP_ROOT = Path(_f5_backup_root) if _f5_backup_root else BASE_DIR / "backups" / "f5"
# Transfert Windows (repli NITROKEY_WINDOWS_SCP_* si vide)
F5_WINDOWS_SCP_HOST = os.environ.get("F5_WINDOWS_SCP_HOST", "").strip() or os.environ.get("F5_SCP_HOST", "").strip()
F5_WINDOWS_SCP_PORT = int(os.environ.get("F5_WINDOWS_SCP_PORT", "0") or os.environ.get("F5_SCP_PORT", "0") or "0") or None
F5_WINDOWS_SCP_USERNAME = os.environ.get("F5_WINDOWS_SCP_USERNAME", "").strip() or os.environ.get("F5_SCP_USERNAME", "").strip()
_f5_win_scp_password_file = os.environ.get("F5_WINDOWS_SCP_PASSWORD_FILE", "").strip() or os.environ.get("F5_SCP_PASSWORD_FILE", "").strip()
_f5_win_scp_password = os.environ.get("F5_WINDOWS_SCP_PASSWORD", "") or os.environ.get("F5_SCP_PASSWORD", "")
if _f5_win_scp_password_file:
    F5_WINDOWS_SCP_PASSWORD = Path(_f5_win_scp_password_file).read_text(encoding="utf-8").strip("\r\n")
else:
    F5_WINDOWS_SCP_PASSWORD = _f5_win_scp_password
F5_WINDOWS_SCP_REMOTE_DIR = (
    os.environ.get("F5_WINDOWS_SCP_REMOTE_DIR", "").strip()
    or os.environ.get("F5_SCP_REMOTE_PARENT_DIR", "").strip()
)
# Alias rétrocompat
F5_SCP_HOST = F5_WINDOWS_SCP_HOST
F5_SCP_PORT = F5_WINDOWS_SCP_PORT
F5_SCP_USERNAME = F5_WINDOWS_SCP_USERNAME
F5_SCP_PASSWORD = F5_WINDOWS_SCP_PASSWORD
F5_SCP_REMOTE_PARENT_DIR = F5_WINDOWS_SCP_REMOTE_DIR

# Arbor AED (adaptateur equipment.adapters.arbor_aed)
_arbor_source = os.environ.get("ARBOR_AED_SOURCE_DIR", "").strip()
ARBOR_AED_SOURCE_DIR = Path(_arbor_source) if _arbor_source else None
_arbor_dc01_dir = os.environ.get("ARBOR_AED_SOURCE_DIR_DC01", "").strip()
_arbor_dc02_dir = os.environ.get("ARBOR_AED_SOURCE_DIR_DC02", "").strip()
ARBOR_AED_SOURCE_DIRS = {
    "DC01": Path(_arbor_dc01_dir) if _arbor_dc01_dir else Path("/app/arbor/incoming/dc01"),
    "DC02": Path(_arbor_dc02_dir) if _arbor_dc02_dir else Path("/app/arbor/incoming/dc02"),
}
ARBOR_AED_ACTIVE_DCS = os.environ.get("ARBOR_AED_ACTIVE_DCS", "").strip()
_arbor_staging = os.environ.get("ARBOR_AED_STAGING_DIR", "").strip()
ARBOR_AED_STAGING_DIR = Path(_arbor_staging) if _arbor_staging else BASE_DIR / "backups" / "arbor_aed" / "staging"
# Dossier mère distant SCP par DC (obligatoire pour chaque DC actif)
ARBOR_AED_REMOTE_PARENT_DIRS = {
    "DC01": os.environ.get("ARBOR_AED_REMOTE_PARENT_DIR_DC01", "").strip(),
    "DC02": os.environ.get("ARBOR_AED_REMOTE_PARENT_DIR_DC02", "").strip(),
}
ARBOR_AED_MOVE_SOURCE = os.environ.get("ARBOR_AED_MOVE_SOURCE", "").lower() in ("1", "true", "yes")
ARBOR_AED_ARCHIVE_AFTER_UPLOAD = os.environ.get(
    "ARBOR_AED_ARCHIVE_AFTER_UPLOAD", "true"
).lower() in ("1", "true", "yes")
_arbor_archive_subdir = os.environ.get("ARBOR_AED_ARCHIVE_SUBDIR", "archive").strip()
ARBOR_AED_ARCHIVE_SUBDIR = _arbor_archive_subdir or "archive"
ARBOR_AED_SCP_HOST = os.environ.get("ARBOR_AED_SCP_HOST", "").strip()
ARBOR_AED_SCP_PORT = int(os.environ.get("ARBOR_AED_SCP_PORT", "0") or "0") or None
ARBOR_AED_SCP_USERNAME = os.environ.get("ARBOR_AED_SCP_USERNAME", "").strip()
_arbor_scp_password_file = os.environ.get("ARBOR_AED_SCP_PASSWORD_FILE", "").strip()
_arbor_scp_password = os.environ.get("ARBOR_AED_SCP_PASSWORD", "")
if _arbor_scp_password_file:
    ARBOR_AED_SCP_PASSWORD = Path(_arbor_scp_password_file).read_text(encoding="utf-8").strip("\r\n")
else:
    ARBOR_AED_SCP_PASSWORD = _arbor_scp_password
